# Generated by Django 3.0.4 on 2020-03-16 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('doi', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('container_title', models.CharField(blank=True, max_length=128)),
                ('publisher', models.CharField(blank=True, max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('issue', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('issued', models.IntegerField()),
                ('page', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['doi'], name='Publication_doi_a6a9ff_idx'),
        ),
    ]
