# Generated by Django 3.0.4 on 2020-03-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0004_auto_20200316_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-update_dt'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
